### ISSUE TITLE
Stats payload is missing an opcode on the /lavalink route

### ISSUE THREAD

**Issue by luaugg** [natanbc/andesite-node#1]
`17:28:00.250 [vert.x-eventloop-thread-2] WARN  c.g.s.l.e.internal.AudioNodeImpl - json payload has no opcode! {"players":0,"playingPlayers":0,"uptime":7905225,"memory":{"free":51945320,"used":63004824,"allocated":114950144,"reservable":1073741823},"cpu":{"cores":4,"systemLoad":0.7412747634754785,"lavalinkLoad":9.074701029098441E-4},"frameStats":null}`

**Comment by natanbc** [comment]
Fixed in https://github.com/natanbc/andesite-node/commit/75479beb00d170e8bf647b51648ee6ef798699a8
