### ISSUE TITLE
Dockerfile broken

### ISSUE THREAD

**Issue by Gelbpunkt** [natanbc/andesite-node#33]
**Describe the bug**
I get `Error: container_linux.go:345: starting container process caused "exec: \"jrt/bin/java\": stat jrt/bin/java: no such file or directory": OCI runtime error` when running the latest docker hub build.

I am using podman and run it inside a systemd unit, however this is an issue with the Dockerfile.

**To Reproduce**
1. `podman pull natanbc/andesite:27ce0cc0861fa884850a5034413daf2020494fc9 && podman run --rm --name andesite -v /opt/andesite:/andesite natanbc/andesite:27ce0cc0861fa884850a5034413daf2020494fc9`

**Expected behavior**
Andesite should launch successfully.

**System (please complete the following information):**
 - OS: Fedora 30
 - Andesite version: 0.18.9
 - Client: irrelevant

**Comment by natanbc** [comment]
The image is working properly.

The issue is that you overwrite the `/andesite` folder, which contains andesite's jar and the bundled java runtime

![image](https://user-images.githubusercontent.com/22461307/63960950-0623df80-ca66-11e9-8b28-13465d7a3ecc.png)
