### ISSUE TITLE
Config file not being detected

### ISSUE THREAD

**Issue by UnspankableGoose** [natanbc/andesite-node#93]
**Describe the bug**
My configuration file is not being detected.

**To Reproduce**
1. Download the latest jar
2. Write a config file

**Expected behavior**
Wanted andesite to connect to a special host/port, connected to default instead

**System (please complete the following information):**
 - OS: Arch Linux
 - Andesite version: 0.20.1
 - Client: Python wavelink

**Additional context**

**Comment by natanbc** [comment]
Can't reproduce

```
andesite » wget -q https://github.com/natanbc/andesite/releases/download/0.20.1-2/andesite-0.20.1-all.jar
andesite » java -jar andesite-0.20.1-all.jar | grep 'Starting HTTP server'
[21:43:57] [main/INFO] [RestHandler]: Starting HTTP server on port 0.0.0.0:5000
^C
andesite » echo 'andesite.transport.http.port=6969' > application.conf
andesite » java -jar andesite-0.20.1-all.jar | grep 'Starting HTTP server'
[21:44:02] [main/INFO] [RestHandler]: Starting HTTP server on port 0.0.0.0:6969
```

**Comment by UnspankableGoose** [comment]
andesite {
  extra-plugins = []
  password = 
  debug-password = null
  log-level = DEBUG
  auto-ytsearch = true
  audio-handler = koe

  node {
    region = us_south
    id = MAIN
  }

  transport {
    http {
      rest = true
      ws = true
      
      bind-address = 127.0.0.1
      port = 2333
    }
  }

  prometheus {
    enabled = true
    path = /metrics
    update-period = 3s
  }

  sentry {
    enabled = false
    dsn = null
    tags = []
    log-level = WARN
  }

  lavaplayer {
    frame-buffer-duration = 5000
    non-allocating = true

    youtube {
      max-playlist-page-count = 10

      #rotation {
      #  ips = ["1.0.0.0/8", "dead:beef::0/32"]
      #  excluded-ips = ["1.0.0.1"]
      #  strategy = "RotateOnBan"
      #  search-triggers-fail = true
      #  retry-limit = -1
      #}
    }
  }

  source {
    bandcamp = true,
    beam = true,
    http = true,
    local = false,
    soundcloud = true,
    twitch = true,
    vimeo = true,
    youtube = true
  }

  lavalink {
    ws-path = /
  }

  magma {
    send-system {
      type = nas

      # Unused if type != nas
      nas-buffer = 400
    }
  }

  koe {
    gateway = v4
    transport = default
    byte-buf-allocator = netty-default
    high-packet-priority = true
    udp-queue {
      buffer = 400
      threads = -1
    }
  }
}

**Comment by UnspankableGoose** [comment]
indents are weird on github

**Comment by natanbc** [comment]
Is the file in the working directory?

**Comment by UnspankableGoose** [comment]
yes

**Comment by UnspankableGoose** [comment]
![image](https://user-images.githubusercontent.com/41350325/106828700-58e8ca00-6650-11eb-819d-bf75d08f36aa.png)

**Comment by UnspankableGoose** [comment]
should i redownload the jar or anything?

**Comment by natanbc** [comment]
That exact config works (after replacing `password =` with `password = ''`), so you're probably running `java` in the wrong directory

```
andesite » java -jar andesite-0.20.1-all.jar | grep 'Starting HTTP server'
[21:50:46] [main/INFO] [RestHandler]: Starting HTTP server on port 127.0.0.1:2333
^C
andesite » cd ..
/tmp » java -jar andesite/andesite-0.20.1-all.jar | grep 'Starting HTTP server'
[21:50:54] [main/INFO] [RestHandler]: Starting HTTP server on port 0.0.0.0:5000
^C 
```

**Comment by UnspankableGoose** [comment]
oh ok ty
